/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Ethernet communication
 * \abstract The Gigabit Ethernet Media Access Controller (GETH) module and the Lightweight IP (LwIP) stack are used to implement a network echo application.
 * \description The TCP/IP protocol provided by the Lightweight IP (LwIP) is used to exchange strings between the board
 *              and a remote client terminal.
 *              The board obtains an IP address and publishes its hostname using the DHCP protocol.
 *              The System Timer Module (STM) is used to update the internal LwIP timers.
 *              The Asynchronous/Synchronous Interface (ASCLIN) module is used for debug logging.
 *
 * \name Ethernet_1_KIT_TC397_TFT
 * \version V2.0.0
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC397_5V_TFT, TC39xXX_B-Step
 * \keywords Ethernet, communication, Ethernet_1, AURIX, UART
 * \documents README.MD
 * \documents https://www.infineon.com/aurix-expert-training/TC39B_iLLD_UM_1_0_1_17_0.chm
 * \lastUpdated 2024-02-27
 *********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxStm.h"
#include "Ifx_reg.h"
#include "IfxScuRcu.h"
#include "IfxGeth_Eth.h"
#include "Configuration.h"
#include "ConfigurationIsr.h"
#include "Ifx_Lwip.h"
#include "UART_Logging.h"
#include <stdio.h>
#include <stdarg.h>

/******************** Hyper Nova Cockpit *****************************************************************/
#include "net_if.h"
#include "dispatcher.h"
#include "transport.h"
#include "frame_codec.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent g_cpuSyncEvent = 0;

static volatile uint8_t got_heater = 0;

/* Dummy sensor values — will be replaced by real HAL drivers later */
static uint8_t sensor_temp     = 25;   /* degrees C */
static uint8_t sensor_humidity = 60;   /* percent */
static uint8_t sensor_fuel     = 80;   /* percent */
static uint8_t sensor_seat     = 0;    /* 0=empty, 1=occupied */

static void dbg_print(const char *fmt, ...)
{
    char buf[128];
    va_list args;
    va_start(args, fmt);
    int n = vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    if (n > 0) {
        sendUARTMessage(buf, (Ifx_SizeT)(n < (int)sizeof(buf) ? n : (int)sizeof(buf) - 1));
    }
}

/* Helper: send CMD_REJECTED reply */
static void send_rejected(uint8_t seq)
{
    uint8_t reply_buf[FRAME_OVERHEAD];  /* 5 bytes: header(3) + CRC(2) */
    uint8_t reply_len = frame_codec_pack(EVT_CMD_REJECTED, seq, NULL, 0, reply_buf);
    if (reply_len > 0) {
        transport_send_event(reply_buf, reply_len);
    }
}

static void test_heater_handler(uint8_t cmd_type, uint8_t seq,
                                const uint8_t *payload, uint8_t len)
{
    (void)cmd_type; (void)payload; (void)len;
    got_heater = 1;
    dbg_print(">>> HANDLER: setHeater, seq=%d\r\n", seq);
    send_rejected(seq);
}

static void test_seat_handler(uint8_t cmd_type, uint8_t seq,
                             const uint8_t *payload, uint8_t len)
{
    (void)cmd_type; (void)payload; (void)len;
    dbg_print(">>> HANDLER: setSeat, seq=%d\r\n", seq);
    send_rejected(seq);
}

static void test_trunk_handler(uint8_t cmd_type, uint8_t seq,
                              const uint8_t *payload, uint8_t len)
{
    (void)cmd_type; (void)payload; (void)len;
    dbg_print(">>> HANDLER: setTrunk, seq=%d\r\n", seq);
    send_rejected(seq);
}

static void test_led_handler(uint8_t cmd_type, uint8_t seq,
                            const uint8_t *payload, uint8_t len)
{
    (void)cmd_type; (void)payload; (void)len;
    dbg_print(">>> HANDLER: setAmbientLED, seq=%d\r\n", seq);
    send_rejected(seq);
}

static void test_sensors_handler(uint8_t cmd_type, uint8_t seq,
                                 const uint8_t *payload, uint8_t len)
{
    (void)cmd_type; (void)payload; (void)len;
    dbg_print(">>> HANDLER: requestSensors, seq=%d\r\n", seq);

    /* Reply with sensorData: [temp][humidity][fuel][seat] */
    uint8_t sensor_payload[4] = {sensor_temp, sensor_humidity, sensor_fuel, sensor_seat};
    uint8_t reply_buf[FRAME_OVERHEAD + 4];  /* 9 bytes: header(3) + payload(4) + CRC(2) */
    uint8_t reply_len = frame_codec_pack(EVT_SENSOR_DATA, seq, sensor_payload, 4, reply_buf);
    if (reply_len > 0) {
        uint8_t ret = transport_send_event(reply_buf, reply_len);
        dbg_print(">>> REPLY: sensorData, seq=%d, ret=%d\r\n", seq, ret);
    }
}
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void core0_main (void)
{
    /* Enable the global interrupts of this CPU */
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event: wait until all CPUs are in CpuX_Main to avoid variables' initialization problems */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    IfxStm_CompareConfig stmCompareConfig;                                  /* STM Configuration declaration                */

    IfxStm_initCompareConfig(&stmCompareConfig);                            /* Initialize a default configuration for STM   */

    stmCompareConfig.triggerPriority     = ISR_PRIORITY_OS_TICK;            /* Priority of the interrupt generated by STM   */
    stmCompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;  /* Select the request source 0                  */
    stmCompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS * 10;   /* First interrupt shall occur after 10 ms      */
    stmCompareConfig.typeOfService       = IfxSrc_Tos_cpu0;                 /* CPU0 serves the interrupts                   */

    IfxStm_initCompare(&MODULE_STM0, &stmCompareConfig);                    /* Initialize the Compare functionality         */

    IfxGeth_enableModule(&MODULE_GETH);                     /* Enable Gigabit Ethernet Media Access Controller (GETH) module*/

    /* Define a MAC Address */
    eth_addr_t ethAddr;
    ethAddr.addr[0] = 0xDE;
    ethAddr.addr[1] = 0xAD;
    ethAddr.addr[2] = 0xBE;
    ethAddr.addr[3] = 0xEF;
    ethAddr.addr[4] = 0xFE;
    ethAddr.addr[5] = 0xED;

//    Ifx_Lwip_init(ethAddr);                                 /* Initialize LwIP with the MAC address                         */
       net_if_init(ethAddr);

       /* Init dispatcher and register all command handlers */
       dispatcher_init();
       dispatcher_register(CMD_SET_HEATER,      test_heater_handler);
       dispatcher_register(CMD_SET_SEAT,        test_seat_handler);
       dispatcher_register(CMD_SET_TRUNK,       test_trunk_handler);
       dispatcher_register(CMD_SET_AMBIENT_LED, test_led_handler);
       dispatcher_register(CMD_REQUEST_SENSORS, test_sensors_handler);
       /* echoInit();  // REMOVED — replaced by our transport + dispatcher */

       uint32_t tick_count = 0;

       while (1)
       {
           /* Service network stack (timers + RX + our transport) */
           net_if_poll();

           /* Send dummy telemetry every ~1 second */
           tick_count++;
           if (tick_count >= 100000)
           {
               tick_count = 0;

               uint8_t payload[4] = {sensor_temp, sensor_humidity, sensor_fuel, sensor_seat};
               uint8_t buf[FRAME_OVERHEAD + 4];
               uint8_t len = frame_codec_pack(EVT_SENSOR_DATA, 0, payload, 4, buf);

               if (len > 0) {
                   transport_send_telemetry(buf, len);
               }
           }
       }
}

/* This interrupt is raised by the STM0 */
IFX_INTERRUPT (updateLwIPStackISR, 0, ISR_PRIORITY_OS_TICK);

/* ISR to update LwIP stack */
void updateLwIPStackISR(void)
{
    /* Configure STM to generate an interrupt in 1 ms */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms++;                                      /* Increase LwIP system time                                    */

    Ifx_Lwip_onTimerTick();                                 /* Every 1 ms LwIP timers are increased for all the enabled
                                                             * protocols (ARP, TCP, DHCP, LINK)                             */
}
